Fixed weathersense startup script

diff --git a/scripts/start_weathersense b/scripts/start_weathersense
--- a/scripts/start_weathersense
+++ b/scripts/start_weathersense
@@ -1,13 +1,11 @@
 #!/bin/bash
 
-sleep 5
-
-
-if [$# != 2 ]; then
+if [ $# != 2 ]; then
     echo "Usage: start_weathersense <version> <user>"
     exit 1
 fi
 
+sleep 5
 
 logdir=../log
 logfile=$logdir/weathersense.log
@@ -17,17 +15,22 @@ weathersense_user=$2
 
 echo "Starting WeatherSense version $version" >> $logfile
 
-cd /weathersense/$version/bin
+bindir=/weathersense/$weathersense_version/bin
 
-echo "Starting VWS" >> $logfile
-su -l $weathersense_user -c ./start_vws $version &>> $logdir/vws.log &
+cd $bindir
+if [ $? != 0 ]; then
+    echo "Directory $bindir does not exist. Start failed"
+    exit 1
+fi
+
+echo `date` "Starting VWS" >> $logfile
+su -l $weathersense_user -c $bindir/start_vws $weathersense_version &>> $logdir/vws.log &
 echo "VWS Started" >> $logfile
 
-echo "Starting weather underground uploader" >> $logfile
-su -l $weathersense_user -c ./start_wunderground-uploader $version &>> $logdir/ws_uploader.log &
+echo `date` "Starting weather underground uploader" >> $logfile
+su -l $weathersense_user -c $bindir/start_wunderground_uploader $weathersense_version &>> $logdir/ws_uploader.log &
 echo "weather underground uploader Started" >> $logfile
 
-echo "Starting Vantage Web Server" >> $logfile
-cd ../../node/VantageConsole
-su -l $weathersense_user -c ./start_web_server $version &>> $logdir/ws_web.log &
+echo `date` "Starting Vantage Web Server" >> $logfile
+su -l $weathersense_user -c $bindir/start_web_server $weathersense_version &>> $logdir/ws_web.log &
 echo "Vantage Web Server Started" >> $logfile
