Updated start scripts

diff --git a/scripts/start_vws b/scripts/start_vws
--- a/scripts/start_vws
+++ b/scripts/start_vws
@@ -2,10 +2,18 @@
 
 version=4.0.0
 
+echo Arg count $#
+
 if [ $# > 0 ]; then
-    version = $1
+    version=$1
 fi
 
 echo "Starting VWS version $version"
-cd /weathersense/$version/bin
+cd /weathersense/$version/bin &> /dev/null
+
+if [ $? != 0 ]; then
+    echo "Directory /weathersense/$version/bin does not exist. Start failed"
+    exit 1
+fi
+
 ./vws /dev/ttyUSB0 ../archive/ ../log/vws_log
diff --git a/scripts/start_web_server b/scripts/start_web_server
--- a/scripts/start_web_server
+++ b/scripts/start_web_server
@@ -3,10 +3,15 @@
 version=4.0.0
 
 if [ $# > 0 ]; then
-    version = $1
+    version=$1
 fi
 
 echo "Starting Vantage Console Web Server version $version"
-cd /weathersense/$version/node/VantageConsole
+cd /weathersense/$version/node/VantageConsole &> /dev/null
+if [ $? != 0 ]; then
+    echo "Directory /weathersense/$version/node/VantageConsole does not exist. Start failed"
+    exit 1
+fi
+
 node ./vantage-console.js
 echo "Vantage Console Web Server started"
diff --git a/scripts/start_wunderground_uploader b/scripts/start_wunderground_uploader
--- a/scripts/start_wunderground_uploader
+++ b/scripts/start_wunderground_uploader
@@ -3,10 +3,15 @@
 version=4.0.0
 
 if [ $# > 0 ]; then
-    version = $1
+    version=$1
 fi
 
 echo "Starting Weather Underground Uploader version $version"
-cd /weathersense/$version/node/VantageUploader
-node ./vantage-uploader.js
+cd /weathersense/$version/node/VantageUploader &> /dev/null
+if [ $? != 0 ]; then
+    echo "Directory /weathersense/$version/node/VantageUploader does not exist. Start failed"
+    exit 1
+fi
+
+node ./vantage-uploader.js KDELEWES163 cePrrTXh
 echo "Started Weather Underground Uploader"
